name: CD
on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-version-pr-or-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install  Dependencies
        run: npm ci
      - name: Create Version PR or Github Release
        id: chengesets
        uses: changesets/action@v1
        with:
          publish: npx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo '${{ toJson(steps.changesets.outputs) }}'
